name: Update GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: ${{ github.ref == "refs/heads/main" }}
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: gh-pages
          commit_message_template: "Automated merge of {source_ref} into target branch {target_branch}"
