name: Update GitHub Pages

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge main to gh-pages branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: ${{ github.token }}
